"""added phone number

Revision ID: e8456c9f44f4
Revises: 20d1a8215992
Create Date: 2026-01-01 03:26:19.264879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8456c9f44f4'
down_revision: Union[str, Sequence[str], None] = '20d1a8215992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(),nullable = False))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'phone_number')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
